### ISSUE TITLE
회원가입 기능 추가

### ISSUE THREAD

**Issue by Sosohy** [6candoit/Plrecipe#2]
## 💡 Feature Issue
회원 가입 기능

## 📝 Comment
- ID,비밀번호,이름,닉네임,전화번호를 작성하여 가입한다.

**Comment by mini-xi** [comment]
good. first issue 이후에 다른 이슈도 같이 추가해야겠습니다.

**Comment by jaehyeon-SMU** [comment]
좋~~습니다!!

**Comment by yunjaeeun** [comment]
수고하셨습니다 :)

**Comment by mini-xi** [comment]
암호화도 완료했습니다
