### ISSUE TITLE
그룹 코스 등록 기능 추가

### ISSUE THREAD

**Issue by mini-xi** [6candoit/Plrecipe#27]
## 💡 Feature Issue

그룹 코스 등록

## 📝 Comment

- 그룹장 및 그룹원이 코스를 그룹에 추가한다.

**Comment by chosoobin37** [comment]
코스 등록을 통해 다양한 데이터를 쌓아봅시다

**Comment by Sosohy** [comment]
그룹에 코스 등록되면 그룹원들끼리 추억을 쌓을 수 있어서 좋은 것 같아요!!

**Comment by mini-xi** [comment]
코스 등록 수고하셨네요
