### ISSUE TITLE
그룹 탈퇴 기능 추가

### ISSUE THREAD

**Issue by mini-xi** [6candoit/Plrecipe#31]
## 💡 Feature Issue

그룹 탈퇴

## 📝 Comment

- 속해 있는 그룹안에 그룹탈퇴를 눌러 그룹에서 탈퇴한다.

**Comment by chosoobin37** [comment]
그룹 탈퇴는 꼭 필요한 기능입니다

**Comment by yunjaeeun** [comment]
인상깊은 코드였습니다 많이 배웠어요 👍

**Comment by chosoobin37** [comment]
그룹탈퇴 !! 멤버 아웃 !!

**Comment by Sosohy** [comment]
확인했습니다!! 그룹 탈퇴할 때 재가입도 가능한지 고민해보면 좋을 것 같아요!

**Comment by mini-xi** [comment]
확인했습니다
