### ISSUE TITLE
게시글 추가내용 작성 기능 추가

### ISSUE THREAD

**Issue by mini-xi** [6candoit/Plrecipe#39]
## 💡 Feature Issue

게시글 추가내용 작성

## 📝 Comment

- 게시글에 코스에 대한 부가적인 설명 및 추가 내용을 작성한다.

**Comment by jaehyeon-SMU** [comment]
와 고생하셨어요!!

**Comment by Sosohy** [comment]
좋습니다~

**Comment by mini-xi** [comment]
수정 맞죠? 잘 된거 같네요
