### ISSUE TITLE
게시글 공개 범위 설정 기능 추가

### ISSUE THREAD

**Issue by mini-xi** [6candoit/Plrecipe#45]
## 💡 Feature Issue

게시글 공개 범위 설정

## 📝 Comment

- 게시글 작성 시 공개 및 비공개 중 하나를 선택해 게시글의 공개 범위를 설정한다.

**Comment by chosoobin37** [comment]
공개 비공개 설정 굿굿

**Comment by Sosohy** [comment]
좋습니다~

**Comment by jaehyeon-SMU** [comment]
이 기능 굉장한데요?

**Comment by mini-xi** [comment]
enum 타입 활용된거 맞나요?
