### ISSUE TITLE
게시글 인원수 설정 기능 추가

### ISSUE THREAD

**Issue by Sosohy** [6candoit/Plrecipe#46]
## 💡 Feature Issue
게시글 인원수 설정 기능 추가

## 📝 Comment
- 게시글 작성 시 인원 설정칸에 1명, 2명, 3명 이상 중 한 가지를 선택해 인원을 설정한다.

**Comment by chosoobin37** [comment]
게시글 인원 설정을 통해 검색조건을 추가하는 기능 좋아요 ~

**Comment by jaehyeon-SMU** [comment]
이 아이디어 정말 좋았던거 같아요!

**Comment by mini-xi** [comment]
고생했어요
